### PR TITLE
Added mash and fermentation sections that are optional

### PR DESCRIPTION
**Pull request by jksnetwork**
I have added sections for both mash details and fermentation details.  They are fairly basic and only show a few things.
capture

I think I did discover a bug in the way BeerSmith exports its BeerXML file though.  If you look at the screen shot the value for Tertiary Temp is 32F but it's using that as the default because BeerSmith isn't including the TERTIARY_TEMP in the export.  They do include DISPLAY_TERTIARY_TEMP but I didn't want to use the display fields as you didn't really use them anywhere else and its kind of not the purpose for them.

I've contacted BeerSmith already asking them to fix the bug and when they do, this should work as well. For now it works fine on 1 and 2 stage fermentation profiles.

### CODE REVIEW

**Comment by dbspringer** [comment]
Thanks for submitting this, I'll take a look and try to get it merged.

**Comment by jksnetwork** [comment]
Just wanted to say I got an update from the creator of BeerSmith.

"Its probably an oversight on my part.  If you edit the Program Files/Reports directory template for exporting these you can probably correct it
pretty easily.  The tags are listed on the BeerSmith forum if you do a quick search."

**Comment by dbspringer** [comment]
Did a tiny bit of cleanup, but otherwise looks great! What's your .org username? I'll list you as a contributor.

**Comment by dbspringer** [comment]
@jksnetwork In case the message didn't get sent out 'cause the pull was closed: send me your .org username and I'll list you as a contributor.

**Comment by jksnetwork** [comment]
Hey I'm not even sure what my .org username is.  No need for credit.

**Comment by dbspringer** [comment]
If you change your mind just let me know. I appreciate your assistance!

**Pull request merged**
